# Generated by Django 4.2.4 on 2023-09-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('vehicle_model', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(unique=True)),
            ],
        ),
    ]
