# Generated by Django 4.2.4 on 2023-09-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtlasApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='vehicle_type',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
